[package]
name = "halo2-fri-gadget"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_10_22" }
halo2_gadgets = {git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_10_22" }
halo2_base = { path = "../halo2-base" }
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves', tag = 'v0.2.0' }
ff = "0.12.0"

[dev-dependencies]
winter-fri = { git = "https://github.com/facebook/winterfell.git" }
winter-math = { git = "https://github.com/facebook/winterfell.git" }
winter-crypto = { git = "https://github.com/facebook/winterfell.git" }
winter-utils = { git = "https://github.com/facebook/winterfell.git" }

