[package]
name = "halo2-fri-gadget"
version = "0.1.0"
edition = "2021"

[dependencies]
goldilocks = { path = "../halo2-ce/arithmetic/goldilocks" }
halo2_proofs = { path = "../halo2-ce/halo2_proofs" }
halo2_base = { path = "../halo2-base" }
ff = "0.12.0"

[dev-dependencies]
winter-fri = { git = "https://github.com/facebook/winterfell.git" }
winter-math = { git = "https://github.com/facebook/winterfell.git" }
winter-crypto = { git = "https://github.com/facebook/winterfell.git" }
winter-utils = { git = "https://github.com/facebook/winterfell.git" }
uint = "0.9.3"
serde = { version = "1.0", default-features = false }
